import { defineWidgetManifest } from './types';

export default defineWidgetManifest({
  id: 'blindspotmonitor',
  name: 'Blind Spot Monitor',
  category: 'awareness',
  description: 'Cars alongside, left and right',
  enabled: false,
  layout: {
    x: 378,
    y: 102,
    width: 800,
    height: 500,
  },
  config: {
    showOnlyWhenOnTrack: false,
    distAhead: 4.5,
    distBehind: 4.5,
    background: {
      opacity: 30,
    },
    width: 20,
    borderSize: 1,
    indicatorColor: 16096779,
    displayMode: 'standard',
    simpleSize: 44,
    simpleVerticalPosition: 50,
    simpleShowCount: true,
    thresholdColorsEnabled: false,
    thresholdColor1: 16096779,
    thresholdColor2: 15680580,
    sessionVisibility: {
      race: true,
      loneQualify: true,
      openQualify: true,
      practice: true,
      offlineTesting: true,
    },
  },
  properties: {
    displayMode: {
      type: 'enum',
      label: 'Display Mode',
      description: 'Visual style of the blind spot indicator.',
      options: [
        { value: 'standard', label: 'Standard' },
        { value: 'simple', label: 'Simple' },
      ],
      control: 'select',
    },
    'background.opacity': {
      type: 'number',
      label: 'Background Opacity',
      min: 0,
      max: 100,
      step: 5,
      units: '%',
    },
    width: {
      type: 'number',
      label: 'Width',
      description: 'Width of the blind spot indicator in pixels.',
      min: 5,
      max: 100,
      step: 1,
      units: 'px',
    },
    borderSize: {
      type: 'number',
      label: 'Border Size',
      description: 'Border thickness of the blind spot indicator in pixels.',
      min: 0,
      max: 20,
      step: 1,
      units: 'px',
    },
    simpleSize: {
      type: 'number',
      label: 'Square Size',
      description: 'Width and height of the indicator square in pixels.',
      min: 20,
      max: 120,
      step: 1,
      units: 'px',
    },
    simpleVerticalPosition: {
      type: 'number',
      label: 'Vertical Position',
      description:
        'Vertical placement within the widget. 0% = top, 50% = centre, 100% = bottom.',
      min: 0,
      max: 100,
      step: 1,
      units: '%',
    },
    simpleShowCount: {
      type: 'boolean',
      label: 'Show Count',
      description: 'Display the number of cars inside the indicator square.',
    },
    thresholdColorsEnabled: {
      type: 'boolean',
      label: 'Colour by Car Count',
      description:
        'Use different colours based on how many cars are in your blind spot.',
    },
    distAhead: {
      type: 'number',
      label: 'Distance Ahead',
      description: 'Distance to car ahead in meters.',
      min: 3,
      max: 6,
      step: 0.1,
      units: 'm',
    },
    distBehind: {
      type: 'number',
      label: 'Distance Behind',
      description: 'Distance to car behind in meters.',
      min: 3,
      max: 6,
      step: 0.1,
      units: 'm',
    },
    showOnlyWhenOnTrack: {
      type: 'boolean',
      label: 'Show only when on track',
      description: 'If enabled, blind spotter will only be shown when driving',
    },
  },
});
