import { defineWidgetManifest } from './types';

export default defineWidgetManifest({
  id: 'fuel',
  name: 'Fuel Calculator',
  enabled: false,
  layout: {
    x: 1102,
    y: 240,
    width: 300,
    height: 520,
  },
  config: {
    showOnlyWhenOnTrack: true,
    fuelUnits: 'L',
    layout: 'vertical',
    showConsumption: true,
    showFuelLevel: true,
    showLapsRemaining: true,
    showMin: true,
    showCurrentLap: true,
    showLastLap: false,
    show3LapAvg: true,
    show10LapAvg: false,
    showMax: true,
    showPitWindow: true,
    showEnduranceStrategy: true,
    showFuelScenarios: true,
    showFuelRequired: true,
    showQualifyConsumption: false,
    showFuelHistory: true,
    fuelHistoryType: 'histogram',
    safetyMargin: 0,
    background: {
      opacity: 85,
    },
    fuelRequiredMode: 'toFinish',
    enableTargetPitLap: false,
    targetPitLap: 15,
    targetPitLapBasis: 'avg',
    enableStorage: true,
    enableLogging: false,
    showFuelStatusBorder: true,
    economyPredictMode: 'live',
    useGeneralFontSize: false,
    useGeneralCompactMode: false,
    sessionVisibility: {
      race: true,
      loneQualify: true,
      openQualify: true,
      practice: true,
      offlineTesting: true,
    },
    layoutConfig: [],
    layoutTree: {
      id: 'root-fuel-default',
      type: 'split',
      direction: 'col',
      children: [
        {
          id: 'box-1',
          type: 'box',
          direction: 'col',
          widgets: ['fuelHeader', 'fuelGauge', 'fuelGrid'],
        },
      ],
    },
    consumptionGridOrder: [
      'curr',
      'avg',
      'max',
      'min',
      'last',
      'avg10',
      'qual',
    ],
    avgLapsCount: 5,
    fuelStatusThresholds: {
      green: 60,
      amber: 30,
      red: 10,
    },
    fuelStatusBasis: 'avg',
    fuelStatusRedLaps: 3,
    widgetStyles: {
      fuelGraph: {
        height: 64,
        labelFontSize: 10,
        valueFontSize: 12,
        barFontSize: 8,
      },
      fuelHeader: {
        labelFontSize: 10,
        valueFontSize: 14,
      },
      fuelConfidence: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelGauge: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelTimeEmpty: {
        labelFontSize: 10,
        valueFontSize: 14,
      },
      fuelGrid: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelScenarios: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelTargetMessage: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelEconomyPredict: {
        labelFontSize: 12,
        valueFontSize: 14,
      },
    },
  },
  properties: {
    useGeneralCompactMode: {
      type: 'boolean',
      label: 'Use General Compact Mode',
      description: 'Syncs with Compact Mode in General tab',
    },
    'background.opacity': {
      type: 'number',
      label: 'Background Opacity',
      min: 0,
      max: 100,
      step: 1,
      units: '%',
    },
    useGeneralFontSize: {
      type: 'boolean',
      label: 'Use General font Sizes',
      description: 'Syncs with Font Size slider in General tab',
    },
    fuelUnits: {
      type: 'enum',
      label: 'Fuel Units',
      description: 'Show fuel in litres or gallons.',
      options: [
        { value: 'L', label: 'Litres (L)' },
        { value: 'gal', label: 'Gallons (gal)' },
      ],
      control: 'select',
    },
    safetyMargin: {
      type: 'number',
      label: 'Safety Margin',
      description: 'Extra fuel added to "To Finish" calculation.',
      control: 'input',
      min: 0,
      max: 50,
      step: 0.1,
    },
    showOnlyWhenOnTrack: {
      type: 'boolean',
      label: 'Show only when on track',
      description: 'If enabled, fuel will only be shown when driving',
    },
    showFuelStatusBorder: {
      type: 'boolean',
      label: 'Show Border Color',
      description: 'Green (safe), Orange (caution), Red (danger)',
    },
    enableStorage: {
      type: 'boolean',
      label: 'Enable Historical Persistence',
      description:
        'Saves the last 10 laps for each car/track to provide immediate estimates.',
    },
    enableLogging: {
      type: 'boolean',
      label: 'Enable Debug Logging',
      description: 'Log comprehensive data to file for troubleshooting.',
    },
    enableTargetPitLap: {
      type: 'boolean',
      label: 'Fixed Target Lap',
      description: 'Enable a specific lap target for strategy',
    },
    fuelHistoryType: {
      type: 'enum',
      label: 'Graph Type',
      options: [
        { value: 'line', label: 'Line Chart' },
        { value: 'histogram', label: 'Histogram' },
      ],
      control: 'select',
    },
  },
});
