import { defineWidgetManifest } from './types';

export default defineWidgetManifest({
  id: 'fuel',
  name: 'Fuel Calculator',
  enabled: false,
  layout: {
    x: 1102,
    y: 240,
    width: 300,
    height: 520,
  },
  config: {
    showOnlyWhenOnTrack: true,
    fuelUnits: 'L',
    layout: 'vertical',
    showConsumption: true,
    showFuelLevel: true,
    showLapsRemaining: true,
    showMin: true,
    showCurrentLap: true,
    showLastLap: false,
    show3LapAvg: true,
    show10LapAvg: false,
    showMax: true,
    showPitWindow: true,
    showEnduranceStrategy: true,
    showFuelScenarios: true,
    showFuelRequired: true,
    showQualifyConsumption: false,
    showFuelHistory: true,
    fuelHistoryType: 'histogram',
    safetyMargin: 0,
    background: {
      opacity: 85,
    },
    fuelRequiredMode: 'toFinish',
    enableTargetPitLap: false,
    targetPitLap: 15,
    targetPitLapBasis: 'avg',
    enableStorage: true,
    enableLogging: false,
    showFuelStatusBorder: true,
    economyPredictMode: 'live',
    useGeneralFontSize: false,
    useGeneralCompactMode: false,
    sessionVisibility: {
      race: true,
      loneQualify: true,
      openQualify: true,
      practice: true,
      offlineTesting: true,
    },
    layoutConfig: [],
    layoutTree: {
      id: 'root-fuel-default',
      type: 'split',
      direction: 'col',
      children: [
        {
          id: 'box-1',
          type: 'box',
          direction: 'col',
          widgets: ['fuelHeader', 'fuelGauge', 'fuelGrid'],
        },
      ],
    },
    consumptionGridOrder: [
      'curr',
      'avg',
      'max',
      'min',
      'last',
      'avg10',
      'qual',
    ],
    avgLapsCount: 5,
    fuelStatusThresholds: {
      green: 60,
      amber: 30,
      red: 10,
    },
    fuelStatusBasis: 'avg',
    fuelStatusRedLaps: 3,
    widgetStyles: {
      fuelGraph: {
        height: 64,
        labelFontSize: 10,
        valueFontSize: 12,
        barFontSize: 8,
      },
      fuelHeader: {
        labelFontSize: 10,
        valueFontSize: 14,
      },
      fuelConfidence: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelGauge: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelTimeEmpty: {
        labelFontSize: 10,
        valueFontSize: 14,
      },
      fuelGrid: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelScenarios: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelTargetMessage: {
        labelFontSize: 10,
        valueFontSize: 12,
      },
      fuelEconomyPredict: {
        labelFontSize: 12,
        valueFontSize: 14,
      },
    },
  },
});
