import { defineWidgetManifest } from './types';

export default defineWidgetManifest({
  id: 'infobar',
  name: 'Information Bar',
  enabled: false,
  layout: {
    x: 0,
    y: 0,
    width: 800,
    height: 60,
  },
  config: {
    enabled: true,
    sessionName: { enabled: true },
    sessionTime: {
      enabled: true,
      mode: 'Remaining',
      totalFormat: 'minimal',
      labelStyle: 'minimal',
    },
    sessionLaps: { enabled: true, mode: 'Elapsed' },
    incidentCount: { enabled: true },
    brakeBias: { enabled: false },
    localTime: { enabled: true },
    sessionClockTime: { enabled: false },
    trackWetness: { enabled: false },
    precipitation: { enabled: false },
    airTemperature: { enabled: false, unit: 'Metric' },
    trackTemperature: { enabled: true, unit: 'Metric' },
    wind: { enabled: false, speedPosition: 'right' },
    trackName: { enabled: false },
    background: { opacity: 80 },
    foreground: { opacity: 70 },
    showOnlyWhenOnTrack: false,
    sessionVisibility: {
      race: true,
      loneQualify: true,
      openQualify: true,
      practice: true,
      offlineTesting: true,
    },
    displayOrder: [
      'sessionName',
      'sessionTime',
      'sessionLaps',
      'incidentCount',
      'brakeBias',
      'localTime',
      'sessionClockTime',
      'trackWetness',
      'precipitation',
      'airTemperature',
      'trackTemperature',
      'wind',
      'trackName',
    ],
  },
  properties: {
    'background.opacity': {
      type: 'number',
      label: 'Background Opacity',
      min: 0,
      max: 100,
      step: 1,
      units: '%',
    },
    'foreground.opacity': {
      type: 'number',
      label: 'Session Bar Opacity',
      min: 0,
      max: 100,
      step: 1,
      units: '%',
    },
    showOnlyWhenOnTrack: {
      type: 'boolean',
      label: 'Show only when on track',
      description: 'Hide the widget when you are not in the car',
    },
  },
});
