import { defineWidgetManifest } from './types';

export default defineWidgetManifest({
  id: 'input',
  name: 'Input Traces',
  menuLabel: 'Input',
  category: 'car',
  description: 'Throttle, brake and clutch traces',
  enabled: true,
  layout: {
    x: 622,
    y: 864,
    width: 396,
    height: 92,
  },
  config: {
    useRawValues: false,
    trace: {
      enabled: true,
      includeThrottle: true,
      includeBrake: true,
      includeAbs: true,
      includeSteer: true,
      includeClutch: false,
      strokeWidth: 3,
      maxSamples: 400,
    },
    bar: {
      enabled: true,
      includeClutch: true,
      includeBrake: true,
      includeThrottle: true,
      includeAbs: true,
    },
    gear: {
      enabled: true,
      size: 100,
      showspeed: true,
      showspeedunit: true,
      swapSpeedUnit: false,
      unit: 'auto',
    },
    abs: {
      enabled: false,
    },
    steer: {
      enabled: true,
      config: {
        style: 'default',
        color: 'light',
      },
    },
    background: {
      opacity: 80,
    },
    showOnlyWhenOnTrack: true,
    displayOrder: ['trace', 'bar', 'gear', 'steer'],
    shiftFlash: {
      enabled: false,
      source: 'redline',
      color: '#9333ea',
    },
    sessionVisibility: {
      race: true,
      loneQualify: true,
      openQualify: true,
      practice: true,
      offlineTesting: true,
    },
  },
  properties: {
    useRawValues: {
      type: 'boolean',
      label: 'Use Raw Inputs',
      description:
        "Disables iRacing's automated input processing, showing direct pedal telemetry without assists like auto-clutch or anti-stall.",
    },
    'background.opacity': {
      type: 'number',
      label: 'Background Opacity',
      min: 0,
      max: 100,
      step: 1,
      units: '%',
    },
    'trace.includeClutch': { type: 'boolean', label: 'Show Clutch Trace' },
    'trace.includeThrottle': { type: 'boolean', label: 'Show Throttle Trace' },
    'trace.includeBrake': { type: 'boolean', label: 'Show Brake Trace' },
    'trace.includeAbs': { type: 'boolean', label: 'Show ABS' },
    'trace.includeSteer': { type: 'boolean', label: 'Show Steering Trace' },
    'trace.strokeWidth': {
      type: 'number',
      label: 'Stroke Width',
      min: 0,
      max: 10,
      step: 1,
      units: 'px',
    },
    'trace.maxSamples': {
      type: 'number',
      label: 'Max Samples',
      min: 40,
      max: 1000,
      step: 1,
      units: ' samples',
    },
    'bar.includeClutch': { type: 'boolean', label: 'Show Clutch Bar' },
    'bar.includeThrottle': { type: 'boolean', label: 'Show Throttle Bar' },
    'bar.includeBrake': { type: 'boolean', label: 'Show Brake Bar' },
    'bar.includeAbs': { type: 'boolean', label: 'Show ABS Indicator' },
    'steer.config.style': {
      type: 'enum',
      label: 'Wheel Style',
      options: [
        { value: 'default', label: 'Default' },
        { value: 'formula', label: 'Formula' },
        { value: 'lmp', label: 'LMP' },
        { value: 'nascar', label: 'NASCAR' },
        { value: 'ushape', label: 'U-Shape' },
        { value: 'ring', label: 'Ring (gear inside)' },
      ],
      control: 'select',
    },
    'steer.config.color': {
      type: 'enum',
      label: 'Wheel Color',
      options: [
        { value: 'light', label: 'Light' },
        { value: 'dark', label: 'Dark' },
      ],
      control: 'select',
    },
    'gear.size': {
      type: 'number',
      label: 'Gear Display Scale',
      description: 'Relative size of the gear number display',
      min: 50,
      max: 150,
      step: 1,
      units: '%',
    },
    'gear.showspeed': {
      type: 'boolean',
      label: 'Show Speed',
      description: 'Show the current speed beneath the gear number',
    },
    'gear.unit': {
      type: 'enum',
      label: 'Speed Unit',
      options: [
        { value: 'auto', label: 'Auto' },
        { value: 'mph', label: 'MPH' },
        { value: 'km/h', label: 'KM/H' },
      ],
    },
    'gear.showspeedunit': { type: 'boolean', label: 'Show Speed Unit Label' },
    'gear.swapSpeedUnit': { type: 'boolean', label: 'Swap Speed & Unit' },
    showOnlyWhenOnTrack: {
      type: 'boolean',
      label: 'Show only when on track',
      description: 'If enabled, inputs will only be shown when driving',
    },
  },
});
