import { DEFAULT_RADAR_TUNING } from '../widgetConfigs';
import { defineWidgetManifest } from './types';

export default defineWidgetManifest({
  id: 'radar',
  name: 'Radar',
  enabled: false,
  layout: {
    x: 760,
    y: 560,
    width: 300,
    height: 300,
  },
  config: {
    range: 30,
    autoHide: true,
    showDistance: 20,
    hideDistance: 25,
    fadeSeconds: 0.3,
    carLength: 4.5,
    carWidth: 1.9,
    sizeByClass: true,
    classSizes: {},
    showWarnings: true,
    warningArcs: false,
    warningArcStyle: 'arc',
    cautionDistance: 7,
    showGapLabel: true,
    showCarNumbers: true,
    showTrackMap: true,
    trackWidth: 10,
    mapOpacity: 10,
    showRings: true,
    ringSpacing: 10,
    hideInPit: true,
    hideInPitBox: true,
    rivalColorMode: 'class',
    rivalCustomColor: null,
    playerColor: 16777215,
    background: {
      opacity: 30,
    },
    edgeFade: 30,
    showCrosshair: true,
    axisMotion: true,
    axisDashLength: 3,
    axisSpeed: 100,
    closeColor: 0xf59e0b,
    alongsideColor: 0xef4444,
    pulseHz: 2.5,
    arcMinDeg: 6,
    arcMaxDeg: 18,
    arcThickness: 7,
    showOverlap: true,
    overlapThreshold: 'door',
    overlapShowPercent: false,
    showDiveWarning: true,
    diveMinClosingKmh: 15,
    diveWarnSeconds: 1.2,
    diveGhost: true,
    diveShowClosing: false,
    diveArcs: true,
    diveArcStyle: 'segments',
    diveArcMinDeg: 6,
    diveArcMaxDeg: 18,
    showHazards: true,
    hazardRange: 500,
    hazardBlinkDistance: 150,
    hazardCrash: true,
    hazardSlow: true,
    hazardOff: true,
    hazardShowLabel: true,
    hazardShowSpeed: true,
    hazardArcs: true,
    hazardArcStyle: 'glow',
    hazardArcMinDeg: 8,
    hazardArcMaxDeg: 24,
    autoProfile: true,
    ovalProfile: null,
    tuning: { ...DEFAULT_RADAR_TUNING },
    showOnlyWhenOnTrack: true,
    sessionVisibility: {
      race: true,
      loneQualify: false,
      openQualify: true,
      practice: true,
      offlineTesting: false,
      warmup: true,
    },
  },
});
